config/routes.rb
Rails.application.routes.draw do
  
  resources :waterings
  resources :plants

  root 'waterings#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :waterings, dependent: :destroy

  def to_s
    name
  end

  def total_volume
    #Pluck genera un arreglo con el volumen de cada uno de los riegos. Reduce suma todos valores del arreglo y retorna la suma.
    waterings.pluck(:volume).reduce(&:+)
  end

  def total_quantity
    waterings.count
  end

  def daily_quantity
    waterings.where(created_at: Date.today.beginning_of_day .. Date.today.end_of_day).count
  end

  def last_watering
    waterings.last&.created_at&.to_date
  end

  def daily_volume
    waterings.where(created_at: Date.today.beginning_of_day .. Date.today.end_of_day).pluck(:volume).reduce(&:+)
  end

  def daily_minutes
    waterings.where(created_at: Date.today.beginning_of_day .. Date.today.end_of_day).pluck(:minutes).reduce(&:+)
  end

end

app/models/watering.rb
class Watering < ApplicationRecord
  belongs_to :plant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plant_params
      params.require(:plant).permit(:name, :kingdom)
    end
end

app/controllers/waterings_controller.rb
class WateringsController < ApplicationController
  before_action :set_watering, only: [:show, :edit, :update, :destroy]

  # GET /waterings
  # GET /waterings.json
  def index
    @waterings = Watering.all
  end

  # GET /waterings/1
  # GET /waterings/1.json
  def show
    
  end

  # GET /waterings/new
  def new
    @watering = Watering.new
    @plants = Plant.all
  end

  # GET /waterings/1/edit
  def edit
    @plants = Plant.all
  end

  # POST /waterings
  # POST /waterings.json
  def create
    @watering = Watering.new(watering_params)

    respond_to do |format|
      if @watering.save
        format.html { redirect_to @watering, notice: 'Watering was successfully created.' }
        format.json { render :show, status: :created, location: @watering }
      else
        format.html { render :new }
        format.json { render json: @watering.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waterings/1
  # PATCH/PUT /waterings/1.json
  def update
    respond_to do |format|
      if @watering.update(watering_params)
        format.html { redirect_to @watering, notice: 'Watering was successfully updated.' }
        format.json { render :show, status: :ok, location: @watering }
      else
        format.html { render :edit }
        format.json { render json: @watering.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waterings/1
  # DELETE /waterings/1.json
  def destroy
    @watering.destroy
    respond_to do |format|
      format.html { redirect_to waterings_url, notice: 'Watering was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_watering
      @watering = Watering.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def watering_params
      params.require(:watering).permit(:volume, :minutes, :plant_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/waterings_helper.rb
module WateringsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gardening</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <a class="navbar-brand" href="/waterings">Gardening</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/waterings">Waterings<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/plants">Plants</a>
            </li>
          </ul>

        </div>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/plants/_form.html.erb
<%= form_with(model: plant, local: true) do |form| %>
  <% if plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :kingdom %>
    <%= form.text_field :kingdom %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<h1>Editing Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plants</h1>

<table class="table">
  <thead class = "thead-dark">
    <tr>
      <th>Name</th>
      <th>Kingdom</th>
      <th>Total watering volume</th>
      <th>Total watering times</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= plant.name %></td>
        <td><%= plant.kingdom %></td>
        <td><%= plant.total_volume %></td>
        <td><%= plant.total_quantity %></td>
        <td><%= link_to 'Show', plant %></td>
        <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
        <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plant', new_plant_path %>

app/views/plants/new.html.erb
<h1>New Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plant.name %>
</p>

<p>
  <strong>Kingdom:</strong>
  <%= @plant.kingdom %>
</p>

<p>
  <strong>Total times watered today:</strong>
  <%= @plant.daily_quantity %>
</p>

<p>
  <strong>Last watering:</strong>
  <%= @plant.last_watering %>
</p>

<p>
  <strong>Minutes watered today:</strong>
  <%= @plant.daily_minutes %>
</p>

<p>
  <strong>Total volume watered today:</strong>
  <%= @plant.daily_volume %>
</p>


<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>

app/views/waterings/_form.html.erb
<%= form_with(model: watering, local: true) do |form| %>
  <% if watering.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(watering.errors.count, "error") %> prohibited this watering from being saved:</h2>

      <ul>
      <% watering.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :volume %>
    <%= form.number_field :volume %>
  </div>

  <div class="field">
    <%= form.label :minutes %>
    <%= form.number_field :minutes %>
  </div>

  <div class="field">
    <%= form.label :plant_id %>
    <%= form.collection_select :plant_id, @plants, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/waterings/edit.html.erb
<h1>Editing Watering</h1>

<%= render 'form', watering: @watering%>

<%= link_to 'Show', @watering %> |
<%= link_to 'Back', waterings_path %>

app/views/waterings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Waterings</h1>

<table class="table">
  <thead class = "thead-dark">
    <tr>
      <th>Volume</th>
      <th>Minutes</th>
      <th>Plant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waterings.each do |watering| %>
      <tr>
        <td><%= watering.volume %></td>
        <td><%= watering.minutes %></td>
        <td><%= watering.plant %></td>
        <td><%= link_to 'Show', watering %></td>
        <td><%= link_to 'Edit', edit_watering_path(watering) %></td>
        <td><%= link_to 'Destroy', watering, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Watering', new_watering_path %>

app/views/waterings/new.html.erb
<h1>New Watering</h1>

<%= render 'form', watering: @watering %>

<%= link_to 'Back', waterings_path %>

app/views/waterings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Volume:</strong>
  <%= @watering.volume %>
</p>

<p>
  <strong>Minutes:</strong>
  <%= @watering.minutes %>
</p>


<p>
  <strong>Plant:</strong>
  <%= @watering.plant %>
</p>

<%= link_to 'Edit', edit_watering_path(@watering) %> |
<%= link_to 'Back', waterings_path %>